#!/bin/sh

package=$(grep -h '^package' *.go |sort |uniq -c |sort -nr |head -n 1 | awk '{print $3}')
if [ -z "$package" ]; then
	printf "failed to find package name" >&2
	exit 1
fi

ver=$(cat VERSION)
if [ -z "$package" ]; then
	printf "failed to find version" >&2
	exit 1
fi

cat <<EOM > version.go
// Code generated by genvers.sh DO NOT EDIT.

package $package

var Version = "$ver"
EOM
